# -- FILE: behave.ini
[behave]
# Use HTML formatter with custom report generator for final report
formatters = behave.formatter.pretty:PrettyFormatter
stdout_capture = True
stderr_capture = True
log_capture = True
logging_level = INFO
logging_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
paths = features
tags = @logout
